export const customers = [
    {id: 1, name: "Proactiv"},
    {id: 2, name: "Home Styles"},
    {id: 3, name: "And You"},
    {id: 4, name: "Bayer"},
    {id: 5, name: "Central"},
    {id: 6, name: "Colgate"},
    {id: 7, name: "Kraft Heinz"},
    {id: 8, name: "Kimberly Clark"},
    {id: 9, name: "Kellogs"},
    {id: 10, name: "Johnson & Johnson"},
    {id: 11, name: "Logitech"},
    {id: 12, name: "Mars"},
    {id: 13, name: "Ela MD"},
    {id: 14, name: "Ferrara"},
    {id: 15, name: "Flexsteel"},
    {id: 16, name: "Mondelez"},
    {id: 17, name: "Gerogia Pacific"},
    {id: 18, name: "Greenworks"},
    {id: 19, name: "HallMark"},
    {id: 20, name: "Natures bounty"},
    {id: 21, name: "NBG Home"},
    {id: 22, name: "Spectrum Brands"},
]